version: "3"
services:
  app:
    build:
      context: "."
      dockerfile: "app.df"
    ports:
      - "8080:8080"
    depends_on:
      - "db"
  db:
    image: "mysql:5"
    environment:
        MYSQL_DATABASE: "interrogate"
        MYSQL_USER: "interrogate"
        MYSQL_PASSWORD: "interrogate"
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
